/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_api_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_api_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Setup Status */
    get: operations["setup_status_api_auth_setup_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap */
    post: operations["bootstrap_api_auth_bootstrap_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Users */
    get: operations["users_api_auth_users_get"];
    put?: never;
    /** Create User */
    post: operations["create_user_api_auth_users_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Activity */
    get: operations["activity_api_activity_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/system/probe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Probe */
    post: operations["probe_api_system_probe_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/catalog/works": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Works */
    get: operations["works_api_catalog_works_get"];
    put?: never;
    /** Add Work */
    post: operations["add_work_api_catalog_works_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/catalog/works/{work_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Work Detail */
    get: operations["work_detail_api_catalog_works__work_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List All */
    get: operations["list_all_api_lists_get"];
    put?: never;
    /** Create List */
    post: operations["create_list_api_lists_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lists/{list_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_api_lists__list_id__get"];
    put?: never;
    post?: never;
    /** Remove List */
    delete: operations["remove_list_api_lists__list_id__delete"];
    options?: never;
    head?: never;
    /** Edit List */
    patch: operations["edit_list_api_lists__list_id__patch"];
    trace?: never;
  };
  "/api/lists/{list_id}/entries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Entry */
    post: operations["add_entry_api_lists__list_id__entries_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lists/{list_id}/entries/{work_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Entry */
    delete: operations["remove_entry_api_lists__list_id__entries__work_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/lists/{list_id}/order": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Reorder */
    put: operations["reorder_api_lists__list_id__order_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Connections */
    get: operations["connections_api_integrations_get"];
    put?: never;
    /** Create Connection */
    post: operations["create_connection_api_integrations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations/{integration_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Connection */
    put: operations["update_connection_api_integrations__integration_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations/{integration_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Connection */
    post: operations["test_connection_api_integrations__integration_id__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/integrations/{integration_id}/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sync Connection */
    post: operations["sync_connection_api_integrations__integration_id__sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/libraries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Libraries */
    get: operations["libraries_api_library_libraries_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/libraries/{library_id}/grants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Replace Grants */
    put: operations["replace_grants_api_library_libraries__library_id__grants_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Assets */
    get: operations["assets_api_library_assets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/library/assets/{asset_id}/match": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Match Asset */
    post: operations["match_asset_api_library_assets__asset_id__match_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Account */
    get: operations["get_account_api_metadata_account_get"];
    /** Save Account */
    put: operations["save_account_api_metadata_account_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/account/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test Account */
    post: operations["test_account_api_metadata_account_test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Preferences */
    get: operations["get_preferences_api_metadata_preferences_get"];
    /** Save Preferences */
    put: operations["save_preferences_api_metadata_preferences_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search */
    get: operations["search_api_metadata_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/books/{provider}/{external_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Preview */
    get: operations["preview_api_metadata_books__provider___external_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/books/{provider}/{external_id}/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Catalog Book */
    post: operations["add_catalog_book_api_metadata_books__provider___external_id__import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/works/{work_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Work Metadata */
    get: operations["work_metadata_api_metadata_works__work_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edit Metadata */
    patch: operations["edit_metadata_api_metadata_works__work_id__patch"];
    trace?: never;
  };
  "/api/metadata/works/{work_id}/source": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Match Source */
    post: operations["match_source_api_metadata_works__work_id__source_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/metadata/works/{work_id}/source/editions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Load Editions */
    post: operations["load_editions_api_metadata_works__work_id__source_editions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ABSConnectionInput */
    ABSConnectionInput: {
      /**
       * Kind
       * @default audiobookshelf
       * @constant
       */
      kind: "audiobookshelf";
      /** Name */
      name: string;
      /** Base Url */
      base_url: string;
      /** Public Url */
      public_url?: string | null;
      /** Token */
      token?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
    };
    /** AccountInput */
    AccountInput: {
      /** Token */
      token?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
    };
    /** AccountView */
    AccountView: {
      /** Configured */
      configured: boolean;
      /** Enabled */
      enabled: boolean;
      /** Status */
      status: string;
      /** Last Error */
      last_error?: string | null;
      /** Last Success At */
      last_success_at?: string | null;
    };
    /** AssetPage */
    AssetPage: {
      /** Items */
      items: components["schemas"]["AssetView"][];
      /** Total */
      total: number;
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
    };
    /** AssetView */
    AssetView: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Library Id
       * Format: uuid
       */
      library_id: string;
      /** Library Name */
      library_name: string;
      /** Title */
      title: string;
      /** Medium */
      medium: string;
      /** State */
      state: string;
      /** Full Content */
      full_content: boolean;
      /** Match Status */
      match_status: string;
      /** Work Ids */
      work_ids: string[];
      /** Version Id */
      version_id: string | null;
      /** Narrators */
      narrators: string[];
      /** Formats */
      formats: string[];
      /** Last Seen At */
      last_seen_at: string | null;
      /** Open Url */
      open_url: string;
    };
    /** AuthView */
    AuthView: {
      user: components["schemas"]["UserView"];
      /** Csrf Token */
      csrf_token: string;
    };
    /** Availability */
    Availability: {
      /**
       * Owned
       * @default false
       */
      owned: boolean;
      /**
       * Ebook
       * @default false
       */
      ebook: boolean;
      /**
       * Audio
       * @default false
       */
      audio: boolean;
      /**
       * Stale
       * @default false
       */
      stale: boolean;
    };
    /** BookData */
    BookData: {
      /**
       * Provider
       * @enum {string}
       */
      provider: "hardcover" | "openlibrary";
      /** External Id */
      external_id: string;
      /** Title */
      title: string;
      /** Authors */
      authors?: string[];
      /** Description */
      description?: string | null;
      /** Publication Year */
      publication_year?: number | null;
      /** Language */
      language?: string | null;
      /** Cover Url */
      cover_url?: string | null;
      /** Subjects */
      subjects?: string[];
      /** Editions */
      editions?: components["schemas"]["EditionData"][];
      /**
       * Editions More
       * @default false
       */
      editions_more: boolean;
      /**
       * Editions Offset
       * @default 0
       */
      editions_offset: number;
      /** Series */
      series?: components["schemas"]["SeriesData"][];
      /** Canonical Id */
      canonical_id?: string | null;
    };
    /** BookPreview */
    BookPreview: {
      book: components["schemas"]["BookData"];
      /**
       * Stale
       * @default false
       */
      stale: boolean;
      /** Warning */
      warning?: string | null;
    };
    /** BootstrapInput */
    BootstrapInput: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /** Bootstrap Token */
      bootstrap_token: string;
      /** Display Name */
      display_name: string;
    };
    /** ConnectionView */
    ConnectionView: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Base Url */
      base_url: string;
      /** Public Url */
      public_url: string;
      /** Enabled */
      enabled: boolean;
      /** Status */
      status: string;
      /** Has Token */
      has_token: boolean;
      /** Version */
      version: string | null;
      /** Scan Supported */
      scan_supported: boolean;
      /** Last Error */
      last_error: string | null;
      /** Last Success At */
      last_success_at: string | null;
    };
    /** Credentials */
    Credentials: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** EditValues */
    EditValues: {
      /** Title */
      title?: string | null;
      /** Authors */
      authors?: string[] | null;
      /** Description */
      description?: string | null;
      /** Language */
      language?: string | null;
      /** Publication Year */
      publication_year?: number | null;
      /** Cover Url */
      cover_url?: string | null;
    };
    /** EditionData */
    EditionData: {
      /** External Id */
      external_id: string;
      /** Title */
      title?: string | null;
      /**
       * Medium
       * @default unknown
       * @enum {string}
       */
      medium: "ebook" | "audio" | "print" | "unknown";
      /** Language */
      language?: string | null;
      /** Narrators */
      narrators?: string[];
      /** Publication Year */
      publication_year?: number | null;
      /** Publisher */
      publisher?: string | null;
      /** Description */
      description?: string | null;
      /** Identifiers */
      identifiers?: {
        [key: string]: string;
      };
      /** Cover Url */
      cover_url?: string | null;
      /** Abridged */
      abridged?: boolean | null;
    };
    /** EntryInput */
    EntryInput: {
      /**
       * Work Id
       * Format: uuid
       */
      work_id: string;
    };
    /** GrantInput */
    GrantInput: {
      /** User Ids */
      user_ids: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LibraryView */
    LibraryView: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Integration Id
       * Format: uuid
       */
      integration_id: string;
      /** Accessible */
      accessible: boolean;
      /** Last Complete Sync */
      last_complete_sync: string | null;
      /** Granted User Ids */
      granted_user_ids: string[];
    };
    /** ListDetail */
    ListDetail: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Shared
       * @default false
       */
      shared: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Count */
      count: number;
      /** Editable */
      editable: boolean;
      /** Items */
      items: components["schemas"]["WorkView"][];
    };
    /** ListInput */
    ListInput: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Shared
       * @default false
       */
      shared: boolean;
    };
    /** ListView */
    ListView: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /**
       * Shared
       * @default false
       */
      shared: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Count */
      count: number;
      /** Editable */
      editable: boolean;
    };
    /** MetadataEdit */
    MetadataEdit: {
      values?: components["schemas"]["EditValues"];
      /** Unlock */
      unlock?: (
        | "title"
        | "authors"
        | "description"
        | "publication_year"
        | "language"
        | "cover_url"
      )[];
    };
    /** MetadataPreferences */
    MetadataPreferences: {
      /**
       * Primary
       * @default hardcover
       * @enum {string}
       */
      primary: "hardcover" | "openlibrary";
      /**
       * Language
       * @default en
       */
      language: string;
      /**
       * Covers
       * @default automatic
       * @enum {string}
       */
      covers: "automatic" | "hardcover" | "openlibrary";
      /** Field Providers */
      field_providers?: {
        [key: string]: "hardcover" | "openlibrary";
      };
    };
    /** MetadataView */
    MetadataView: {
      /** Fields */
      fields: {
        [key: string]: unknown;
      };
      /** Sources */
      sources: components["schemas"]["SourceView"][];
      /** Versions */
      versions: components["schemas"]["VersionView"][];
      /** Versions Total */
      versions_total: number;
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
      /** Cover Choices */
      cover_choices: string[];
    };
    /** OperationView */
    OperationView: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Kind */
      kind: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** OrderInput */
    OrderInput: {
      /** Work Ids */
      work_ids: string[];
    };
    /** SearchPage */
    SearchPage: {
      /**
       * Provider
       * @enum {string}
       */
      provider: "hardcover" | "openlibrary";
      /** Items */
      items: components["schemas"]["BookData"][];
      /** Page */
      page: number;
      /** Has More */
      has_more: boolean;
      /**
       * Stale
       * @default false
       */
      stale: boolean;
      /** Warning */
      warning?: string | null;
    };
    /** SeriesData */
    SeriesData: {
      /** External Id */
      external_id: string;
      /** Name */
      name: string;
      /** Position */
      position?: string | null;
      /**
       * Compilation
       * @default false
       */
      compilation: boolean;
    };
    /** SetupView */
    SetupView: {
      /** Needs Setup */
      needs_setup: boolean;
    };
    /** SourceView */
    SourceView: {
      /**
       * Provider
       * @enum {string}
       */
      provider: "hardcover" | "openlibrary";
      /** External Id */
      external_id: string;
      /** Title */
      title: string;
      /**
       * Fetched At
       * Format: date-time
       */
      fetched_at: string;
      /** Cover Url */
      cover_url: string | null;
      /** Editions More */
      editions_more: boolean;
      /** Series */
      series: components["schemas"]["SeriesData"][];
    };
    /** UserInput */
    UserInput: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /** Display Name */
      display_name: string;
      /**
       * Role
       * @default member
       * @enum {string}
       */
      role: "admin" | "member" | "viewer";
    };
    /** UserView */
    UserView: {
      /** Id */
      id: string;
      /** Username */
      username: string;
      /** Display Name */
      display_name: string;
      /** Role */
      role: string;
      /** Can Automate */
      can_automate: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VersionView */
    VersionView: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Medium */
      medium: string;
      /** Title */
      title: string | null;
      /** Language */
      language: string | null;
      /** Narrators */
      narrators: string[];
      /** Publication Year */
      publication_year: number | null;
      /** Identifiers */
      identifiers: {
        [key: string]: unknown;
      };
      /** Owned */
      owned: boolean;
      /** Needs Review */
      needs_review: boolean;
    };
    /** WorkInput */
    WorkInput: {
      /** Title */
      title: string;
      /** Authors */
      authors?: string[];
      /** Description */
      description?: string | null;
      /** Language */
      language?: string | null;
      /** Publication Year */
      publication_year?: number | null;
    };
    /** WorkPage */
    WorkPage: {
      /** Items */
      items: components["schemas"]["WorkView"][];
      /** Total */
      total: number;
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
    };
    /** WorkView */
    WorkView: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Authors */
      authors: string[];
      /** Description */
      description: string | null;
      /** Language */
      language: string | null;
      /** Publication Year */
      publication_year: number | null;
      /** Cover Url */
      cover_url: string | null;
      /** Provisional */
      provisional: boolean;
      availability: components["schemas"]["Availability"];
    };
    /** MatchInput */
    app__api__library__MatchInput: {
      /** Work Id */
      work_id: string | null;
    };
    /** MatchInput */
    app__api__metadata__MatchInput: {
      /**
       * Provider
       * @enum {string}
       */
      provider: "hardcover" | "openlibrary";
      /** External Id */
      external_id: string;
      /**
       * Confirm Match
       * @default false
       */
      confirm_match: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness_api_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readiness_api_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  setup_status_api_auth_setup_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetupView"];
        };
      };
    };
  };
  bootstrap_api_auth_bootstrap_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BootstrapInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Credentials"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthView"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  users_api_auth_users_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserView"][];
        };
      };
    };
  };
  create_user_api_auth_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activity_api_activity_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OperationView"][];
        };
      };
    };
  };
  probe_api_system_probe_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OperationView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  works_api_catalog_works_get: {
    parameters: {
      query?: {
        q?: string;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_work_api_catalog_works_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  work_detail_api_catalog_works__work_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_all_api_lists_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListView"][];
        };
      };
    };
  };
  create_list_api_lists_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detail_api_lists__list_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_list_api_lists__list_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_list_api_lists__list_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ListInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_entry_api_lists__list_id__entries_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EntryInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_entry_api_lists__list_id__entries__work_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
        work_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reorder_api_lists__list_id__order_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        list_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  connections_api_integrations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"][];
        };
      };
    };
  };
  create_connection_api_integrations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ABSConnectionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_connection_api_integrations__integration_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        integration_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ABSConnectionInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_connection_api_integrations__integration_id__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        integration_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_connection_api_integrations__integration_id__sync_post: {
    parameters: {
      query?: never;
      header: {
        "idempotency-key": string;
      };
      path: {
        integration_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OperationView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  libraries_api_library_libraries_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LibraryView"][];
        };
      };
    };
  };
  replace_grants_api_library_libraries__library_id__grants_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        library_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assets_api_library_assets_get: {
    parameters: {
      query?: {
        work_id?: string | null;
        library_id?: string | null;
        needs_review?: boolean;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  match_asset_api_library_assets__asset_id__match_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        asset_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["app__api__library__MatchInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_account_api_metadata_account_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountView"];
        };
      };
    };
  };
  save_account_api_metadata_account_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  test_account_api_metadata_account_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountView"];
        };
      };
    };
  };
  get_preferences_api_metadata_preferences_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetadataPreferences"];
        };
      };
    };
  };
  save_preferences_api_metadata_preferences_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MetadataPreferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetadataPreferences"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_api_metadata_search_get: {
    parameters: {
      query: {
        q: string;
        provider?: "automatic" | "hardcover" | "openlibrary";
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_api_metadata_books__provider___external_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: "hardcover" | "openlibrary";
        external_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BookPreview"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_catalog_book_api_metadata_books__provider___external_id__import_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: "hardcover" | "openlibrary";
        external_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  work_metadata_api_metadata_works__work_id__get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetadataView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_metadata_api_metadata_works__work_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MetadataEdit"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  match_source_api_metadata_works__work_id__source_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["app__api__metadata__MatchInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  load_editions_api_metadata_works__work_id__source_editions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        work_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["app__api__metadata__MatchInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
